name: ci

on: [push, pull_request]

jobs:
    ci:
        strategy:
            fail-fast: false
            matrix:
                os:
                    - macos-10.15
                    - ubuntu-20.04
                ocaml-version:
                    - '4.11.1+flambda'
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2.3.4
              with:
                  submodules: recursive
            - uses: avsm/setup-ocaml@v1.1.3
              with:
                  ocaml-version: ${{ matrix.ocaml-version }}
            - uses: actions/cache@v2.1.2
              with:
                  path: ~/.opam/download-cache/
                  key: ${{ runner.os }}-ocaml-opam-${{ hashFiles('dune-project') }}
                  restore-keys: ${{ runner.os }}-ocaml-opam-
            - run: make dep
            - run: make coverage
            - uses: codecov/codecov-action@v1.0.14
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./_coverage/coverage.json
            - run: make doc
              if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-20.04' && matrix.ocaml-version == '4.11.1+flambda'
            - uses: peaceiris/actions-gh-pages@v3.7.3
              if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-20.04' && matrix.ocaml-version == '4.11.1+flambda'
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: ./_build/default/_doc/_html/
